/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bb155d55-0d17-4e6d-9db5-4e95bb25cdc4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4LWgmHoES",
    "aws_user_pools_web_client_id": "5n0p77oggvt618mmrmsdol4rie",
    "oauth": {}
};


export default awsmobile;
